---
title: "Linear Spline Knot Estimation"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(EBARS)
library(splines)
library(segmented)
library(ggplot2)
library(ggpubr)
source("bars.R")
source("Linear_Spline_Estimation.R")
```

```{r}
f1 = function(x) {
  knots = c(0.5)
  beta = c(1,-1,1)
  B = bs(x,knots=knots,degree=1,intercept=TRUE,Boundary.knots=c(0,1))
  y = B%*%beta
  return(y)
}

f2 = function(x) {
  knots = c(0.3,0.7)
  beta = c(2,-1,-2,-1)
  B = bs(x,knots=knots,degree=1,intercept=TRUE,Boundary.knots=c(0,1))
  y = B%*%beta
  return(y)
}

f3 = function(x) {
  knots = c(0.2,0.2,0.5,0.7)
  beta = c(0,-1,1,0,1,0)
  B = bs(x,knots=knots,degree=1,intercept=TRUE,Boundary.knots=c(0,1))
  y = B%*%beta
  return(y)
}
```

```{r}
n_exp = 50 # experiment number
noises = c(0.4,0.3,0.4)
fs = list(f1,f2,f3); ks = c(1,2,4)
xis = list(c(0.5),c(0.3,0.7),c(0.2,0.2,0.5,0.7))
idxs = list(c(1),c(2:3),c(4:7))
error_array = array(dim=c(3,7,n_exp))
dim_names = list(c("EBARS","LSE","Segmented"),c("Case 1 Knot 1","Case 2 Knot 1","Case 2 Knot 2","Case 3 Knot 1","Case 3 Knot 2","Case 3 Knot 3","Case 3 Knot 4"))
dimnames(error_array) = dim_names
```

+ Plot

```{r}
set.seed(1234)
m = 200
x_train = runif(m,0,1)
# case 1
y_train_1 = f1(x_train)
y_obs_1 = y_train_1 + rnorm(m,0,noises[1])
p1 = ggplot() + geom_point(aes(x_train,y_obs_1),size=0.6,col="red") + geom_line(aes(x_train,y_train_1)) + theme(axis.title.x=element_blank(),axis.title.y=element_blank())
# case 2
y_train_2 = f2(x_train)
y_obs_2 = y_train_2 + rnorm(m,0,noises[2])
p2 = ggplot() + geom_point(aes(x_train,y_obs_2),size=0.6,col="red") + geom_line(aes(x_train,y_train_2)) + theme(axis.title.x=element_blank(),axis.title.y=element_blank())
# case 3 
y_train_3 = f3(x_train)
y_obs_3 = y_train_3 + rnorm(m,0,noises[3])
p3 = ggplot() + geom_point(aes(x_train,y_obs_3),size=0.6,col="red") + geom_line(aes(x_train,y_train_3)) + theme(axis.title.x=element_blank(),axis.title.y=element_blank())

# arrange in one page
pdf(file=file.path("plots","knot_estimation.pdf"),height = 3)
ggarrange(p1,p2,p3,ncol=3)
dev.off()
```


+ Run Simulation

```{r}
time.start = Sys.time()
set.seed(1234)
m_train = 500
for(n in 1:n_exp) {
  for(i in 1:3) {
    # generate training data
  k = ks[i]; f = fs[[i]]; noise = noises[[i]]
  xi = xis[[i]]; idx = idxs[[i]]
  x_train = runif(m_train)
  y_train = f(x_train)
  y_obs = y_train + rnorm(m_train,0,noise)
  
  # EBARS
  ebars_linear = ebars(x_train,y_obs,k=k,n=1000,degree=1,intercept=TRUE)
  ebars_linear$mcmc(burns=1000,steps=1000)
  xi_ebars = sort(ebars_linear$knots())
  error_array[1,idx,n] = xi-xi_ebars
  
  # Linear Spline Estimation
  init_lse = quantile(x_train, probs=seq(0,1,length.out=(k+2))[2:(k+1)])
  xi_lse = sort(LSE(x_train,y_obs,init_lse))
  error_array[2,idx,n] = xi-xi_lse
  
  # segmented method
  init_seg = quantile(x_train, probs=seq(0,1,length.out=(k+2))[2:(k+1)])
  fit.lm = lm(y_obs~x_train)
  fit.seg = segmented(fit.lm,seg.Z=~x_train,psi=init_seg)
  xi_seg = sort(fit.seg$psi[,2])
  error_array[3,idx,n] = xi-xi_seg
  }
}
time.end = Sys.time()
print(time.end-time.start)
```

+ Summary Data

```{r}
error_mean = array(dim=c(3,7)); dimnames(error_mean) = dim_names
error_sd = error_mean
error_df = data.frame(error_mean)

for(i in 1:3) {
  for(j in 1:7) {
    error_mean[i,j] = mean(abs(error_array[i,j,]))
    error_sd[i,j] = sd(abs(error_array[i,j,]))
    error_df[i,j] = paste0(round(error_mean[i,j],digits=4),"(",round(error_sd[i,j],digits=4),")")
  }
}

print(error_df)
```

```{r}
write.csv(error_df,file=file.path("tables","knot_estimation-500.csv"))
```

