---
title: "Manifold Fitting"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(EBARS)
library(plot3D)
library(ggplot2)
source("Principal_Manifold_Estimation.R")
```

## Curve Fitting
+ Spiral in R^2
```{r}
set.seed(1234)
```

```{r}
I = 1000; I.test = 1000
theta = seq(0, 6*pi, length.out=I)
x = cbind(2*(theta+4)^(0.7)*cos(theta), 2*(theta+4)^(0.7)*sin(theta))

sd = 0.3
xobs = x + cbind(rnorm(I,0,sd), rnorm(I,0,sd))
```

```{r}
ggplot() + geom_point(aes(xobs[,1],xobs[,2]),size=0.6,col="red") +
  theme(axis.title.x=element_blank(),axis.title.y=element_blank())
```

```{r}
# EBARS
time.start = Sys.time()
result.ebars = manifold_fitting(xobs, d=1)
time.end = Sys.time()
print(time.end-time.start)
```

```{r}
center = (result.ebars$lower+result.ebars$upper)/2
radius = abs(result.ebars$upper-result.ebars$lower)/2
x.ebars = result.ebars$map(seq(center-radius*0.99,center+radius*0.99,length.out=I.test))
ggplot() + geom_path(aes(x.ebars[,1],x.ebars[,2])) +
  theme(axis.title.x=element_blank(),axis.title.y=element_blank())
```

```{r,include=FALSE}
# Principal Manifold Estimation
time.start = Sys.time()
result.pme = PME(xobs,d=1,print.MSDs = F)
time.end = Sys.time()
```

```{r}
print(time.end - time.start)
```


```{r}
t.pme = seq(-100,100,length.out=I.test)
x.pme = t(sapply(t.pme,function(t) {return(result.pme$embedding.map(t))}))
ggplot() + geom_path(aes(x.pme[,1],x.pme[,2])) + xlim(range(xobs[,1])) + ylim(range(xobs[,2])) +
  theme(axis.title.x=element_blank(),axis.title.y=element_blank())
```


+ space spiral in R^3
```{r}
set.seed(1234)
```

```{r}
I = 1000; I.test = 1000
theta = seq(0, 6*pi, length.out=I)
x = cbind(2*(theta+4)^(0.7)*cos(theta), 2*(theta+4)^(0.7)*sin(theta), -2*(theta+4)^(0.7))

sd = 0.3
xobs = x + cbind(rnorm(I,0,sd), rnorm(I,0,sd), rnorm(I,0,sd))
```

```{r}
scatter3D(xobs[,1], xobs[,2], xobs[,3],
          theta = 15, phi = 30,
          pch = 20, box=TRUE, cex = 0.2, colkey = FALSE, 
          border="black", shade=0.8, 
          bty = "g", ticktype = "detailed",
          main="")
```

```{r}
# EBARS
time.start = Sys.time()
result.ebars = manifold_fitting(xobs, d=1)
time.end = Sys.time()
print(time.end-time.start)
```

```{r}
center = (result.ebars$lower+result.ebars$upper)/2
radius = abs(result.ebars$upper-result.ebars$lower)/2
x.ebars = result.ebars$map(seq(center-radius*0.99,center+radius*0.99,length.out=I.test))
```

```{r}
scatter3D(x.ebars[,1], x.ebars[,2], x.ebars[,3],
          theta = 15, phi = 30, col = "black",
          pch = 20, box=TRUE, cex = 0.2, colkey = FALSE, 
          border="black", shade=0.8, 
          bty = "g", ticktype = "detailed",
          main="")
```

```{r,include=FALSE}
# Principal Manifold Estimation
time.start = Sys.time()
result.pme = PME(xobs, d=1)
time.end = Sys.time()
```

```{r}
print(time.end-time.start)
```

```{r}
t.pme = seq(-100,100,length.out=I.test)
x.pme = t(sapply(t.pme,function(t) {return(result.pme$embedding.map(t))}))
```

```{r}
scatter3D(x.pme[,1], x.pme[,2], x.pme[,3],
          theta = 15, phi = 30, col = "black",
          pch = 20, box=TRUE, cex = 0.2, colkey = FALSE, 
          border="black", shade=0.8, 
          bty = "g", ticktype = "detailed",
          main="")
```

## Surface Fitting
+ Swiss Roll 
```{r}
I = 1000; I.test = 1000
theta = 1.5*pi*(1+2*runif(I))
x_2 = 21*runif(I)
x_1 = theta*cos(theta)
x_3 = theta*sin(theta)
x = cbind(x_1,x_2,x_3)
```

