---
title: "Manifold Estimation"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(Matrix)
library(RSpectra)
library(plot3D)
```


```{r}
library(EBARS)
library(umap)
library(tsne)
library(vegan)
library(Rdimtools)
library(FLGP)
```

```{r}
set.seed(1234)
```

+ Manifold Estimation

```{r}
I = 1000
theta = c(seq(-pi/2,0,length.out=I/2), seq(pi/2,pi,length.out=I/2))
x = rbind(cbind(cos(theta[1:(I/2)]),1+sin(theta[1:(I/2)])),
          cbind(seq(1,2,length.out=500),-2*seq(1,2,length.out=500)+3),
          cbind(3+cos(theta[(I/2+1):I]),-1+sin(theta[(I/2+1):I])))
xobs = rbind(x + cbind(rnorm(I+500,0,0.02),rnorm(I+500,0,0.02)))

ggplot() + geom_point(aes(xobs[,1],xobs[,2]),col="red",pch=16,cex=0.5) + 
  xlab("x_1") + ylab("x_2")
```

```{r}
I = 2000
theta = runif(I,0,1.5*pi)
x = cbind(cos(theta),sin(theta))
xobs = x + cbind(rnorm(I,0,0.02),rnorm(I,0,0.02))

ggplot() + geom_point(aes(xobs[,1],xobs[,2]),col="red",pch=16,cex=0.5) + 
  xlab("x_1") + ylab("x_2")
```

```{r}
I = 2000
theta = runif(I,0,6*pi)
x = cbind(theta, sin(theta))
xobs = x + cbind(rnorm(I,0,0.1),rnorm(I,0,0.1))

ggplot() + geom_point(aes(xobs[,1],xobs[,2]),col="red",pch=16,cex=0.5) + 
  xlab("x_1") + ylab("x_2")
```

```{r}
I = 2000
theta = seq(0, 6*pi, length.out=I)
x = cbind(2*(theta+4)^(0.7)*cos(theta), 2*(theta+4)^(0.7)*sin(theta))
sd = 0.3
xobs = x + cbind(rnorm(I,0,sd), rnorm(I,0,sd))

ggplot() + geom_point(aes(xobs[,1],xobs[,2]),col="red",pch=16,cex=0.5) + 
  xlab("x_1") + ylab("x_2")
```

```{r}
## Swiss Roll
I = 2000
theta = runif(I,pi,5*pi)
x_2 = 21*runif(I)
x_1 = 3*theta*cos(theta)
x_3 = 3*theta*sin(theta)
x = cbind(x_1,x_2,x_3)
xobs = x + matrix(rnorm(3*I,0,1.5),I,3)
scatter3D(xobs[,1], xobs[,2], xobs[,3],
          theta = 20, phi = 15, colvar = theta,
          ylim = c(-15,15),
          pch = 20, box=TRUE, cex = 0.5, colkey = FALSE, 
          border="black", shade=0.8, 
          bty = "g", ticktype = "detailed",
          main="")
```


+ Local Anchor Embedding
```{r}
Z = cross_similarity_lae_cpp(xobs, xobs, r=20, gl="normalized")
res.lae = eigs_sym(Z%*%rowScale(t(Z),1/colSums(Z)),k=3)
u.lae = res.lae$vectors[,2:3]
```

```{r}
manifold.lae = lae_eigenmap(xobs, s=400, r=3, ndim=3)
u.lae = manifold.lae$eigenvectors[,2:3]
```

```{r}
ggplot() + geom_point(aes(u.lae,xobs[,1]),col="red",pch=16,cex=0.5) + 
  xlab("u") + ylab("x_1")
```

```{r}
scatter3D(u.lae[,1], u.lae[,2], xobs[,3],
          theta = 20, phi = 15, colvar = theta,
          pch = 20, box=TRUE, cex = 0.5, colkey = FALSE, 
          border="black", shade=0.8, 
          bty = "g", ticktype = "detailed",
          main="")
```


```{r}
ggplot() + geom_point(aes(u.lae,xobs[,2]),col="red",pch=16,cex=0.5) + 
  xlab("u") + ylab("x_2")
```

```{r}
embedding_map <- function(x, d) {
  Z = cross_similarity_lae_cpp(xobs, xobs, r=20, gl="normalized")
  res.lae = eigs_sym(Z%*%rowScale(t(Z),1/colSums(Z)),k=d+1)
  u.lae = res.lae$vectors[,-1]
  return(u.lae)
}

result.ebars = manifold_fitting(xobs, d=2, embedding_map)
center = (result.ebars$lower+result.ebars$upper)/2
radius = abs(result.ebars$upper-result.ebars$lower)/2
u.ebars = cbind(runif(I.test,center[1]-radius[1]*0.99,center[1]+radius[1]*0.99),runif(I.test,center[2]-radius[2]*0.6,center[2]+radius[2]*0.6))
x.ebars = result.ebars$map(u.ebars)
```

```{r}
scatter3D(x.ebars[,1], x.ebars[,2], x.ebars[,3],
          theta = 20, phi = 15, colvar = u.ebars[,1],
          xlim = range(xobs[,1]), ylim = c(-20,20), zlim = range(xobs[,3]),
          pch = 20, box=TRUE, cex = 0.5, colkey = FALSE, 
          border="black", shade=0.8, 
          bty = "g", ticktype = "detailed",
          main="")
```

+ Laplacian Eigenmap
```{r}
manifold.lapeig = do.lapeig(xobs, ndim=2, kernelscale=1, type=c("knn",20), weighted=TRUE)
u.lapeig = manifold.lapeig$Y
```

```{r}
ggplot() + geom_point(aes(u.lapeig,xobs[,1]),col="red",pch=16,cex=0.5) + 
  xlab("u") + ylab("x_1")
```


```{r}
ggplot() + geom_point(aes(u.lapeig,xobs[,2]),col="red",pch=16,cex=0.5) + 
  xlab("u") + ylab("x_2")
```

```{r}
embedding_map <- function(x, d) {
  u = do.lapeig(x, ndim=d, kernelscale=1, type=c("knn",20), weighted=TRUE)$Y
  return(cbind(u))
}

result.ebars = manifold_fitting(xobs, d=1, embedding_map)
center = (result.ebars$lower+result.ebars$upper)/2
radius = abs(result.ebars$upper-result.ebars$lower)/2
x.ebars = result.ebars$map(seq(center-radius,center+radius,length.out=I))
ggplot() + geom_path(aes(x.ebars[,1],x.ebars[,2]),col="red") + 
  xlab("x_1") + ylab("x_2")
```

```{r}
x_1 = predict(loess(xobs[,1]~u.lapeig, span=0.2), seq(min(u.lapeig), max(u.lapeig), length.out=I))
x_2 = predict(loess(xobs[,2]~u.lapeig, span=0.2), seq(min(u.lapeig), max(u.lapeig), length.out=I))
ggplot() + geom_path(aes(x_1,x_2),col="red") + 
  xlab("x_1") + ylab("x_2")
```


+ Uniform Manifold Approximation Map
```{r}
custom.config = umap.defaults
custom.config$n_components = 1
custom.config$min_dist = 0.5
custom.config$n_neighbors = 20
custom.config$metric = "euclidean"
manifold.umap = umap(xobs, config=custom.config)
```

```{r}
u.umap = manifold.umap$layout
```


```{r}
ggplot() + geom_point(aes(u.umap[,1],xobs[,1]),col="red",pch=16,cex=0.5) + 
  xlab("u") + ylab("x_1")
```

```{r}
ggplot() + geom_point(aes(u.umap[,1],xobs[,2]),col="red",pch=16,cex=0.5) + 
  xlab("u") + ylab("x_2")
```

+ t-SNE
```{r}
manifold.tsne = tsne(xobs, k=1)
u.tsne = manifold.tsne
```


```{r}
ggplot() + geom_point(aes(u.tsne[,1],xobs[,1]),col="red",pch=16,cex=0.5) + 
  xlab("u") + ylab("x_1")
```

```{r}
ggplot() + geom_point(aes(u.tsne[,1],xobs[,2]),col="red",pch=16,cex=0.5) + 
  xlab("u") + ylab("x_2")
```


+ Isomap
```{r}
manifold.isomap = isomap(dist(xobs), ndim=1, k=10)
u.isomap = manifold.isomap$points
```

```{r}
scatter3D(u.isomap[,1], u.isomap[,2], xobs[,3],
          theta = 20, phi = 15, colvar = theta,
          pch = 20, box=TRUE, cex = 0.5, colkey = FALSE, 
          border="black", shade=0.8, 
          bty = "g", ticktype = "detailed",
          main="")
```

```{r}
embedding_map <- function(x, d) {
  u = isomap(dist(x), ndim=d, k=10)$points
  return(u)
}

result.ebars = manifold_fitting(xobs, d=1, embedding_map)
u.ebars = result.ebars$u
x.ebars = result.ebars$fitted
```


```{r}
scatter3D(x.ebars[,1], x.ebars[,2], x.ebars[,3],
          theta = 20, phi = 15, colvar = u.ebars[,1],
          ylim = c(-15,15),
          pch = 20, box=TRUE, cex = 0.5, colkey = FALSE, 
          border="black", shade=0.8, 
          bty = "g", ticktype = "detailed",
          main="")
```

```{r}
gse = rep(NA,I)
for(i in c(1:I)) {
  distances = c(1:I)
  for(j in c(1:I)) {
    distances[j] = sqrt(sum((x.ebars[i,]-x[j,])^2))
  }
  gse[i] = min(distances)
}
gmse = mean(gse)
gmse
```


```{r}
ggplot() + geom_point(aes(u.isomap[,1],xobs[,2]),col="red",pch=16,cex=0.5) +
  xlab("") + ylab("")
```


```{r}
ggplot() + geom_line(aes(x.ebars[,1],x.ebars[,2]),col="red") + 
  xlab("") + ylab("")
```
