---
title: "Linear Spline Knot Estimation"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(EBARS)
library(splines)
library(segmented)
library(ggplot2)
library(ggpubr)
library(grid)
source("Linear_Spline_Estimation.R")
```

```{r}
f1 = function(x) {
  knots = c(0.5)
  beta = c(1,-1,1)
  B = bs(x,knots=knots,degree=1,intercept=TRUE,Boundary.knots=c(0,1))
  y = B%*%beta
  return(y)
}

f2 = function(x) {
  knots = c(0.3,0.7)
  beta = c(2,-1,-2,-1)
  B = bs(x,knots=knots,degree=1,intercept=TRUE,Boundary.knots=c(0,1))
  y = B%*%beta
  return(y)
}

f3 = function(x) {
  knots = c(0.2,0.2,0.5,0.7)
  beta = c(0,-1,1,0,1,0)
  B = bs(x,knots=knots,degree=1,intercept=TRUE,Boundary.knots=c(0,1))
  y = B%*%beta
  return(y)
}
```

```{r}
n_exp = 50 # experiment number
noises = c(0.4,0.3,0.4)
fs = list(f1,f2,f3); ks = c(1,2,4)
xis = list(c(0.5),c(0.3,0.7),c(0.2,0.2,0.5,0.7))
idxs = list(c(1),c(2:3),c(4:7))
error_array = array(dim=c(3,7,n_exp))
dim_names = list(c("EBARS","LSE","Segmented"),c("Case 1 Knot 1","Case 2 Knot 1","Case 2 Knot 2","Case 3 Knot 1","Case 3 Knot 2","Case 3 Knot 3","Case 3 Knot 4"))
dimnames(error_array) = dim_names
```

+ Plot

```{r}
set.seed(1234)
m = 200
x_train = runif(m,0,1)
# case 1
y_train_1 = f1(x_train)
y_obs_1 = y_train_1 + rnorm(m,0,noises[1])
p1 = ggplot() + geom_point(aes(x_train,y_obs_1),size=0.6,col="red") + geom_line(aes(x_train,y_train_1)) + theme(axis.title.x=element_blank(),axis.title.y=element_blank())
# case 2
y_train_2 = f2(x_train)
y_obs_2 = y_train_2 + rnorm(m,0,noises[2])
p2 = ggplot() + geom_point(aes(x_train,y_obs_2),size=0.6,col="red") + geom_line(aes(x_train,y_train_2)) + theme(axis.title.x=element_blank(),axis.title.y=element_blank())
# case 3 
y_train_3 = f3(x_train)
y_obs_3 = y_train_3 + rnorm(m,0,noises[3])
p3 = ggplot() + geom_point(aes(x_train,y_obs_3),size=0.6,col="red") + geom_line(aes(x_train,y_train_3)) + theme(axis.title.x=element_blank(),axis.title.y=element_blank())

# arrange in one page
pdf(file=file.path("figures","knot_estimation.pdf"), height = 3, width=10.5)
ggarrange(p1,p2,p3,ncol=3)
dev.off()
```

+ Posterior distribution

```{r}
set.seed(1234)
# case 1
m_1 = 500; sd_1 = noises[1]
x_1 = runif(m_1)
y_1 = f1(x_1) + rnorm(m_1,0,sd_1)
# EBARS
ebars_1 = ebars(x_1,y_1,gamma=2,c=0.3,n=1000,degree=1,intercept=TRUE)
ebars_1$mcmc(burns=5000,steps=5000)
samples_1 = ebars_1$samples()
nums_1 = sapply(samples_1, function(xi) {return(length(xi))})
points_1 = unlist(samples_1)
p_11 = ggplot(mapping=aes(x=nums_1)) + geom_bar(aes(y=after_stat(prop)), width = 0.6) + ylab("") + xlab("") + geom_vline(aes(xintercept=mean(nums_1)), color="red", linetype="dashed") + scale_x_discrete(limits=factor(1:5))
p_12 = ggplot(mapping=aes(x=points_1)) + geom_density(adjust=5) + ylab("") + xlab("") + xlim(0, 1)

# case 2
m_2 = 500; sd_2 = noises[2]
x_2 = runif(m_2)
y_2 = f2(x_2) + rnorm(m_2,0,sd_2)
# EBARS
ebars_2 = ebars(x_2,y_2,gamma=2,c=0.3,n=1000,degree=1,intercept=TRUE)
ebars_2$mcmc(burns=5000,steps=5000)
samples_2 = ebars_2$samples()
nums_2 = sapply(samples_2, function(xi) {return(length(xi))})
points_2 = unlist(samples_2)
p_21 = ggplot(mapping=aes(x=nums_2)) + geom_bar(aes(y=after_stat(prop)), width = 0.6) + ylab("") + xlab("") + geom_vline(aes(xintercept=mean(nums_2)), color="red", linetype="dashed") + scale_x_discrete(limits=factor(1:5))
p_22 = ggplot(mapping=aes(x=points_2)) + geom_density(adjust=1) + ylab("") + xlab("") + xlim(0, 1)

# case 3
m_3 = 500; sd_3 = noises[3]
x_3 = runif(m_3)
y_3 = f3(x_3) + rnorm(m_3,0,sd_3)
# EBARS
ebars_3 = ebars(x_3,y_3,gamma=2,c=0.3,n=1000,degree=1,intercept=TRUE)
ebars_3$mcmc(burns=5000,steps=5000)
samples_3 = ebars_3$samples()
nums_3 = sapply(samples_3, function(xi) {return(length(xi))})
points_3 = unlist(samples_3)
p_31 = ggplot(mapping=aes(x=nums_3)) + geom_bar(aes(y=after_stat(prop)), width = 0.6) + ylab("") + xlab("") + geom_vline(aes(xintercept=mean(nums_3)), color="red", linetype="dashed") + scale_x_discrete(limits=factor(1:5))
p_32 = ggplot(mapping=aes(x=points_3)) + geom_density(adjust=1) + ylab("") + xlab("") + xlim(0, 1)

pdf(file=file.path("figures","knot_inference.pdf"),width=8,height=6)
annotate_figure(ggarrange(p_11,p_12,p_21,p_22,p_31,p_32,ncol=2,nrow=3,align="hv"),top="",left="")
dev.off()
```

+ Knot Inference

```{r}
set.seed(1234)
# case 1
m_1 = 500; sd_1 = noises[1]
x_1 = runif(m_1)
y_1 = f1(x_1) + rnorm(m_1,0,sd_1)
# EBARS
ebars_1 = ebars(x_1,y_1,k=1,n=1000,degree=1,intercept=TRUE)
ebars_1$mcmc(burns=5000,steps=5000)
nodes_1 = sapply(ebars_1$samples(), function(xi) {return(xi)})

# case 2
m_2 = 500; sd_2 = noises[2]
x_2 = runif(m_2)
y_2 = f2(x_2) + rnorm(m_2,0,sd_2)
# EBARS
ebars_2 = ebars(x_2,y_2,k=2,n=1000,degree=1,intercept=TRUE)
ebars_2$mcmc(burns=5000,steps=5000)
nodes_2 = sapply(ebars_2$samples(), function(xi) {return(xi)})

# case 3
m_3 = 500; sd_3 = noises[3]
x_3 = runif(m_3)
y_3 = f3(x_3) + rnorm(m_3,0,sd_3)
# EBARS
ebars_3 = ebars(x_3,y_3,k=4,n=1000,degree=1,intercept=TRUE)
ebars_3$mcmc(burns=5000,steps=5000)
nodes_3 = sapply(ebars_3$samples(), function(xi) {return(xi)})
```

+ Run Simulations

```{r, include=FALSE}
time.start = Sys.time()
set.seed(1234)
m_train = 200
for(n in 1:n_exp) {
  for(i in 1:3) {
  print(paste0("The ",n,"-th experiment\n"))
  # generate training data
  k = ks[i]; f = fs[[i]]; noise = noises[[i]]
  xi = xis[[i]]; idx = idxs[[i]]
  x_train = runif(m_train)
  y_train = f(x_train)
  y_obs = y_train + rnorm(m_train,0,noise)
  
  # EBARS
  ebars_linear = ebars(x_train,y_obs,k=k,n=1000,degree=1,intercept=TRUE)
  ebars_linear$mcmc(burns=5000,steps=5000)
  if(k==1) {
    xi_ebars = mean(sapply(ebars_linear$samples(), function(xi) {return(xi)}))
  } else {
    xi_ebars = rowMeans(sapply(ebars_linear$samples(), function(xi) {return(xi)}))
  }
  error_array[1,idx,n] = xi-xi_ebars
  
  if(FALSE) {
  # Linear Spline Estimation
  init_lse = quantile(x_train, probs=seq(0,1,length.out=(k+2))[2:(k+1)])
  xi_lse = sort(LSE(x_train,y_obs,init_lse))
  error_array[2,idx,n] = xi-xi_lse
  
  # segmented method
  init_seg = quantile(x_train, probs=seq(0,1,length.out=(k+2))[2:(k+1)])
  fit.lm = lm(y_obs~x_train)
  fit.seg = segmented(fit.lm,seg.Z=~x_train,npsi=k)
  xi_seg = sort(fit.seg$psi[,2])
  error_array[3,idx,n] = xi-xi_seg
  }
  }
}
time.end = Sys.time()
print(time.end-time.start)
# Time difference of 1.018486 hours
```

+ Summary Data

```{r}
error_mean = array(dim=c(3,7)); dimnames(error_mean) = dim_names
error_sd = error_mean
error_df = data.frame(error_mean)

for(i in 1:3) {
  for(j in 1:7) {
    error_mean[i,j] = mean(abs(error_array[i,j,]))
    error_sd[i,j] = sd(abs(error_array[i,j,]))
    error_df[i,j] = paste0(round(error_mean[i,j],digits=4),"(",round(error_sd[i,j],digits=4),")")
  }
}

print(error_df)
```

```{r}
write.csv(error_df,file=file.path("../tables","knot_estimation-500.csv"))
```

