---
title: "Estimate broken stick"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(EBARS)
library(umap)
library(princurve)

source("G:/HeJunhui/research/2023/exampleEBARS/exampleEBARS/manifold/algo/Principal_Manifold_Estimation.R")
```

+ Generate data

```{r}
set.seed(1234)
```

```{r}
mani = "arcs"
n_exp = 20
fileroot = "G:/HeJunhui/research/2023/exampleEBARS/exampleEBARS/manifold"
# model parameters
I = 500
D = 2; d = 1
sd = 0.2

embedding_map <- function(x, d) {
  custom.config = umap.defaults
  custom.config$n_components = d
  custom.config$min_dist = 0.3
  custom.config$n_neighbors = 20
  u = umap(x, config=custom.config)$layout
  return(u)
}
```


```{r,include=FALSE}
t.start = Sys.time()
for(rep in 1:n_exp) {
  # generate samples
  theta = c(seq(-pi/2,0,length.out=I/2), seq(pi/2,pi,length.out=I/2))
  x = 10*rbind(cbind(cos(theta[1:(I/2)]),1+sin(theta[1:(I/2)])),
          cbind(2+cos(theta[(I/2+1):(2*I/2)]),0+sin(theta[(I/2+1):(2*I/2)])))
  xobs = x + cbind(rnorm(I,0,sd), rnorm(I,0,sd))
  cat("broken arcs noisy samples with dim (", dim(xobs), ")\n")
  write.csv(t(xobs), file=file.path(fileroot, "dataset", mani, paste0(rep,"_less.csv")))
  
  # manifold estimation
  # TSME
  t1 = Sys.time()
  result.ebars = manifold_fitting(xobs, d, embedding_map)
  x.ebars = result.ebars$fitted
  t2 = Sys.time()
  cat(paste0("Trial ",rep," TSME\n"))
  print(t2-t1)
  write.csv(t(x.ebars), file=file.path(fileroot, "output", mani, paste0("tsme_trial",rep,"_less.csv")))
  
  # PME
  t1 = Sys.time()
  result.pme = PME(xobs, d, embedding_map, tuning.para.seq=exp(-5:5), epsilon=0.1)
  x.pme = result.pme$fitted
  t2 = Sys.time()
  cat(paste0("Trial ",rep," PME\n"))
  print(t2-t1)
  write.csv(t(x.pme), file=file.path(fileroot, "output", mani, paste0("pme_trial",rep,"_less.csv")))
  
  # PC
  t1 = Sys.time()
  result.pc = principal_curve(xobs, smoother="smooth_spline")
  x.pc = result.pc$s
  t2 = Sys.time()
  cat(paste0("Trial ",rep," PC\n"))
  print(t2-t1)
  write.csv(t(x.pc), file=file.path(fileroot, "output", mani, paste0("pc_trial",rep,"_less.csv")))
}
t.end = Sys.time()
```

```{r}
print(t.end-t.start)
# Time difference of 24.51353 mins
# Time difference of 15.78024 mins
```
