---
title: "MNIST"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(bigmemory)
library(umap)
library(tsne)
library(microbenchmark)
library(ggplot2)
library(EBARS)
library(ks)
```

```{r}
datapath = "G:/Phd/Data/MNIST/mnist"
```

```{r}
x.mnist = read.big.matrix(file.path(datapath, "images.csv"), has.row.names = TRUE, type = "double", skip = 1)
y.mnist = read.big.matrix(file.path(datapath, "labels.csv"), has.row.names = TRUE, type = "double", skip = 1)
```


```{r}
image(matrix(x.mnist[1,],28,28)[,28:1],col=gray.colors(100,0,1))
```


+ Uniform Manifold Approximation Map
```{r}
custom.config = umap.defaults
custom.config$n_components = 2
# custom.config$min_dist = 0.5
# custom.config$n_neighbors = 20
# custom.config$metric = "euclidean"
microbenchmark(umap={manifold.umap = umap(x.mnist[,], config=custom.config)}, times=1)
```

```{r}
u.umap = manifold.umap$layout
```

```{r}
ggplot() + geom_point(aes(u.umap[,1],u.umap[,2],color=as.factor(y.mnist[,])))
```

+ Extract one digit
```{r}
digit = 6
idx = which(y.mnist[,]==digit)
x.digit = x.mnist[idx,]
```

```{r}
m = 500
x = x.digit[sample.int(nrow(x.digit),m),]
```

```{r}
image(matrix(x[1,],28,28)[,28:1],col=gray.colors(100,0,1))
```


```{r}
custom.config = umap.defaults
custom.config$n_components = 2
microbenchmark(umap={manifold.umap = umap(x, n_components=2)}, times=1)
```

```{r}
u = manifold.umap$layout
ggplot() + geom_point(aes(u[,1],u[,2]))
```

+ Resize images

```{r}
resize = function(img, new_width, new_height) {
  new_img = apply(img, 2, function(y){return (spline(y, n = new_height)$y)})
  new_img = t(apply(new_img, 1, function(y){return (spline(y, n = new_width)$y)}))

  new_img[new_img < 0] = 0
  new_img = round(new_img)

  return (new_img)
}
```

```{r}
x.res = t(apply(x,1,function(x) {c(resize(matrix(x,28,28),10,10))}))
```

```{r}
image(matrix(x.res[5,],10,10)[,10:1],col=gray.colors(100,0,1))
```




+ TSME

```{r}
embedding_map <- function(x, d) {
  u = umap(x, n_components=d)$layout
  return(u)
}
```

```{r}
t1 = Sys.time()
manifold = manifold_fitting(x.res, 1, embedding_map)
t2 = Sys.time()
```

```{r}
t2-t1
```

```{r}
fit = manifold$fitted
```

```{r}
img = round(fit[5,])
img[img<0] = 0
img = matrix(img,10,10)

image(img[,10:1],col=gray.colors(100,0,1))
```


+ Pen digit

```{r}
x.pen = as.matrix(read.csv("G:/Phd/Data/Pen/pendigits-master/pendigits_sta8_train.csv", header=FALSE))
y.pen = read.csv("G:/Phd/Data/Pen/pendigits-master/pendigits_label_train.csv", header=FALSE)[,1]
```

```{r}
digit = 4
idx = which(y.pen==digit)
x = x.pen[idx,]
```

```{r}
image(matrix(x[3,],8,8)[,8:1],col=gray.colors(100,0,1))
```

+ Kernel Density Estimate

```{r}
n = 2000
idx = sample.int(nrow(u.umap),n)
ggplot() + geom_point(aes(u.umap[idx,1],u.umap[idx,2]))
```


```{r}
den = kde(u.umap)
u.new = rkde(n,den)
ggplot() + geom_point(aes(u.new[,1],u.new[,2]))
```

