---
title: "Estimate Swiss roll"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(EBARS)
library(vegan)

source("Principal_Manifold_Estimation.R")
```

+ Generate data

```{r}
set.seed(1234)
```

```{r}
## Swiss Roll
I = 2000
theta = runif(I,pi,5*pi)
x_2 = 21*runif(I)
x_1 = 3*theta*cos(theta)
x_3 = 3*theta*sin(theta)
x = cbind(x_1,x_2,x_3)
xobs = x + matrix(rnorm(3*I,0,1.5),I,3)
scatter3D(xobs[,1], xobs[,2], xobs[,3],
          theta = 20, phi = 15, colvar = theta,
          ylim = c(-15,15),
          pch = 20, box=TRUE, cex = 0.5, colkey = FALSE, 
          border="black", shade=0.8, 
          bty = "g", ticktype = "detailed",
          main="")
```

```{r}
N = 5000
theta_grid = runif(N,pi,5*pi)
mesh = cbind(3*theta_grid*cos(theta_grid), 21*runif(N), 3*theta_grid*sin(theta_grid))
scatter3D(mesh[,1], mesh[,2], mesh[,3],
          theta = 20, phi = 15, colvar = theta_grid,
          ylim = c(-15,15),
          pch = 20, box=TRUE, cex = 0.5, colkey = FALSE, 
          border="black", shade=0.8, 
          bty = "g", ticktype = "detailed",
          main="")
```

```{r}
gse = rep(NA,I)
for(i in c(1:I)) {
  gse[i] = min(apply(mesh,1,function(p) {return(sum((xobs[i,]-p)^2))}))
}
gmse = mean(gse)
gmse
```

+ Manifold Estimation

```{r}
# TSME
embedding_map <- function(x, d) {
  u = isomap(dist(x), ndim=d, k=20)$points
  return(u)
}

t1 = Sys.time()
result.ebars = manifold_fitting(xobs, d=2, embedding_map)
t2 = Sys.time()
print(t2 - t1)
u.ebars = result.ebars$u
x.ebars = result.ebars$fitted
```

```{r}
scatter3D(x.ebars[,1], x.ebars[,2], x.ebars[,3],
          theta = 20, phi = 15, colvar = theta,
          ylim = c(-15,15),
          pch = 20, box=TRUE, cex = 0.5, colkey = FALSE, 
          border="black", shade=0.8, 
          bty = "g", ticktype = "detailed",
          main="")
```

```{r}
gse.tsme = rep(NA,I)
for(i in c(1:I)) {
  gse.tsme[i] = min(apply(mesh,1,function(p) {return(sum((x.ebars[i,]-p)^2))}))
}
gmse.tsme = mean(gse.tsme)
gmse.tsme
```

```{r, include=FALSE}
# PME
t1 = Sys.time()
result.pme = PME(xobs, d=2, embedding_map)
t2 = Sys.time()
x.pme = result.pme$fitted
```

```{r}
print(t2 - t1)
```

```{r}
scatter3D(x.pme[,1], x.pme[,2], x.pme[,3],
          theta = 20, phi = 15, colvar = theta,
          ylim = c(-15,15),
          pch = 20, box=TRUE, cex = 0.5, colkey = FALSE, 
          border="black", shade=0.8, 
          bty = "g", ticktype = "detailed",
          main="")
```

```{r}
gse.pme = rep(NA,I)
for(i in c(1:I)) {
  gse.pme[i] = min(apply(mesh,1,function(p) {return(sum((x.pme[i,]-p)^2))}))
}
gmse.pme = mean(gse.pme)
gmse.pme
```

