---
title: "Estimate Spiral"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(EBARS)
library(vegan)
library(princurve)

source("G:/HeJunhui/research/2023/exampleEBARS/exampleEBARS/manifold/algo/Principal_Manifold_Estimation.R")
```

+ Generate data

```{r}
set.seed(1234)
```

```{r}
I = 1200
theta = seq(0, 6*pi, length.out=I)
x = cbind(2*(theta+4)^(0.7)*cos(theta), 2*(theta+4)^(0.7)*sin(theta))
sd = 0.3
xobs = x + cbind(rnorm(I,0,sd), rnorm(I,0,sd))

ggplot() + geom_point(aes(xobs[,1],xobs[,2]),col="red",pch=16,cex=0.5) + 
  xlab("") + ylab("")
```

```{r}
N = 3000
theta_grid = seq(0, 6*pi, length.out=N)
mesh = cbind(2*(theta_grid+4)^(0.7)*cos(theta_grid), 2*(theta_grid+4)^(0.7)*sin(theta_grid))
```

```{r}
gse = rep(NA,I)
for(i in c(1:I)) {
  gse[i] = min(apply(mesh,1,function(p) {return(sum((xobs[i,]-p)^2))}))
}
gmse = mean(gse)
gmse
```


+ Manifold Estimation

```{r}
# TSME
embedding_map <- function(x, d) {
  u = isomap(dist(x), ndim=d, k=8)$points
  return(u)
}

result.ebars = manifold_fitting(xobs, d=1, embedding_map)
u.ebars = result.ebars$u
x.ebars = result.ebars$fitted
```

```{r}
ggplot() + geom_point(aes(x.ebars[,1],x.ebars[,2]),col="red",pch=16,cex=0.5) +
  xlab("") + ylab("")
```


```{r}
gse.tsme = rep(NA,I)
for(i in c(1:I)) {
  gse.tsme[i] = min(apply(mesh,1,function(p) {return(sum((x.ebars[i,]-p)^2))}))
}
gmse.tsme = mean(gse.tsme)
gmse.tsme
```



```{r, include=FALSE}
# PME
result.pme = PME(xobs, d=1, embedding_map)
x.pme = result.pme$fitted
```

```{r}
ggplot() + geom_point(aes(x.pme[,1],x.pme[,2]),col="red",pch=16,cex=0.5) +
  xlab("") + ylab("")
```

```{r}
gse.pme = rep(NA,I)
for(i in c(1:I)) {
  gse.pme[i] = min(apply(mesh,1,function(p) {return(sum((x.pme[i,]-p)^2))}))
}
gmse.pme = mean(gse.pme)
gmse.pme
```

```{r, include=FALSE}
# Principal Curve
result.pc = principal_curve(xobs, smoother="smooth_spline")
x.pc = result.pc$s
```

```{r}
ggplot() + geom_point(aes(x.pc[,1],x.pc[,2]),col="red",pch=16,cex=0.5) +
  xlab("") + ylab("")
```

```{r}
gse.pc = rep(NA,I)
for(i in c(1:I)) {
  gse.pc[i] = min(apply(mesh,1,function(p) {return(sum((x.pc[i,]-p)^2))}))
}
gmse.pc = mean(gse.pc)
gmse.pc
```

```{r}
ggplot() + geom_point(aes(u.ebars[,1],xobs[,2]),col="red",pch=16,cex=0.5) +
  xlab("") + ylab("")
```
