---
title: "Manifold Fitting"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(EBARS)
library(plot3D)
library(ggplot2)
source("Principal_Manifold_Estimation.R")
```

+ Manifold Fitting
```{r,include=FALSE}
time.start = Sys.time()
pdf(file=file.path("plots","manifold_fitting.pdf"))
par(mfrow=c(3,3))
par(mar=c(1,2,1,2))

set.seed(1234)

# spiral in R^2
I = 1000; I.test = 1000
theta = seq(0, 6*pi, length.out=I)
x = cbind(2*(theta+4)^(0.7)*cos(theta), 2*(theta+4)^(0.7)*sin(theta))
sd = 0.35
xobs = x + cbind(rnorm(I,0,sd), rnorm(I,0,sd))
plot(xobs[,1],xobs[,2],col="red",xlab="",ylab="",pch=16,cex=0.5)
# EBARS
result.ebars = manifold_fitting(xobs, d=1)
center = (result.ebars$lower+result.ebars$upper)/2
radius = abs(result.ebars$upper-result.ebars$lower)/2
x.ebars = result.ebars$map(seq(center-radius*0.99,center+radius*0.99,length.out=I.test))
plot(x.ebars[,1],x.ebars[,2],type="l",xlab="",ylab="",xlim=range(xobs[,1]),ylim=range(xobs[,2]),lwd=1.5)
# PME
result.pme = PME(xobs,d=1,print.MSDs = F)
t.pme = seq(-100,100,length.out=I.test)
x.pme = t(sapply(t.pme,function(t) {return(result.pme$embedding.map(t))}))
plot(x.pme[,1],x.pme[,2],type="l",xlab="",ylab="",xlim=range(xobs[,1]),ylim=range(xobs[,2]),lwd=1.5)

# spiral in R^3
I = 1000; I.test = 1000
theta = seq(0, 6*pi, length.out=I)
x = cbind(2*(theta+4)^(0.7)*cos(theta), 2*(theta+4)^(0.7)*sin(theta), -2*(theta+4)^(0.7))
sd = 0.4
xobs = x + cbind(rnorm(I,0,sd), rnorm(I,0,sd), rnorm(I,0,sd))
scatter3D(xobs[,1], xobs[,2], xobs[,3],
          theta = 20, phi = 30,
          pch = 20, box=TRUE, cex = 0.2, colkey = FALSE, 
          border="black", shade=0.8, 
          bty = "g", ticktype = "detailed",
          main="")
# EBARS
result.ebars = manifold_fitting(xobs, d=1)
center = (result.ebars$lower+result.ebars$upper)/2
radius = abs(result.ebars$upper-result.ebars$lower)/2
x.ebars = result.ebars$map(seq(center-radius*0.99,center+radius*0.99,length.out=I.test))
scatter3D(x.ebars[,1], x.ebars[,2], x.ebars[,3],
          theta = 20, phi = 30, type = "l", lwd = 2,
          xlim = range(xobs[,1]), ylim = range(xobs[,2]), zlim = range(xobs[,3]),
          pch = 20, box=TRUE, cex = 0.2, colkey = FALSE, 
          border="black", shade=0.8, 
          bty = "g", ticktype = "detailed",
          main="")
# PME
result.pme = PME(xobs, d=1, print.MSDs = F)
t.pme = seq(-100,100,length.out=I.test)
x.pme = t(sapply(t.pme,function(t) {return(result.pme$embedding.map(t))}))
scatter3D(x.pme[,1], x.pme[,2], x.pme[,3],
          theta = 15, phi = 30, type = "l", lwd = 2,
          xlim = range(xobs[,1]), ylim = range(xobs[,2]), zlim = range(xobs[,3]),
          pch = 20, box=TRUE, cex = 0.2, colkey = FALSE, 
          border="black", shade=0.8, 
          bty = "g", ticktype = "detailed",
          main="")

## Swiss Roll
I = 2000; I.test = 3000
theta = runif(I,pi,5*pi)
x_2 = 21*runif(I)
x_1 = 3*theta*cos(theta)
x_3 = 3*theta*sin(theta)
x = cbind(x_1,x_2,x_3)
xobs = x + matrix(rnorm(3*I,0,0.5),I,3)
scatter3D(xobs[,1], xobs[,2], xobs[,3],
          theta = 20, phi = 15, colvar = theta,
          ylim = c(-20,20),
          pch = 20, box=TRUE, cex = 0.5, colkey = FALSE, 
          border="black", shade=0.8, 
          bty = "g", ticktype = "detailed",
          main="")
# EBARS
result.ebars = manifold_fitting(xobs, d=2)
center = (result.ebars$lower+result.ebars$upper)/2
radius = abs(result.ebars$upper-result.ebars$lower)/2
t.ebars = cbind(runif(I.test,center[1]-radius[1]*0.99,center[1]+radius[1]*0.99),runif(I.test,center[2]-radius[2]*0.6,center[2]+radius[2]*0.6))
x.ebars = result.ebars$map(t.ebars)
scatter3D(x.ebars[,1], x.ebars[,2], x.ebars[,3],
          theta = 20, phi = 15, colvar = t.ebars[,1], 
          xlim = range(xobs[,1]), ylim = c(-20,20), zlim = range(xobs[,3]),
          pch = 20, box=TRUE, cex = 0.5, colkey = FALSE, 
          border="black", shade=0.8, 
          bty = "g", ticktype = "detailed",
          main="")
# PME
result.pme = PME(xobs, d=2, print.MSDs = F)
t.pme = cbind(runif(I.test,-10,10),runif(I.test,-10,10))
x.pme = t(sapply(1:I.test,function(i) {return(result.pme$embedding.map(t.pme[i,]))}))
scatter3D(x.pme[,1], x.pme[,2], x.pme[,3],
          theta = 20, phi = 15, colvar = t.pme[,1],
          xlim = range(xobs[,1]), ylim = c(-20,20), zlim = range(xobs[,3]),
          pch = 20, box=TRUE, cex = 0.5, colkey = FALSE, 
          border="black", shade=0.8, 
          bty = "g", ticktype = "detailed",
          main="")
dev.off()
time.end = Sys.time()
```

```{r}
print(time.end - time.start)
```

