---
title: "Surface Spline Regression Table"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,include=FALSE}
library(EBARS)
library(mgcv)
```

+ Function

```{r}
f1 = function(x) {
  return(-40*(exp(-(x[,1]-0.2)^2/0.1-(x[,2]-0.3)^2/0.1)+exp(-(x[,1]-0.7)^2/0.1-(x[,2]-0.8)^2/0.1)))
}

f2 = function(x) {
  return(50*exp(-(x[,1]-0.5)^2/0.01-(x[,2]-0.5)^2/0.01))
}

f3 = function(x) {
  xi_1 = c(0.2,0.5)
  xi_2 = c(0.4,0.4,0.4,0.4,0.7)
  beta = c(-1.21, 0.28, 1.08, -2.35, 0.43, 0.51, -0.57, -0.55, -0.56, -0.89, -0.48, -1.00, -0.78,  0.06,  0.96, -0.11, -0.51, -0.91, -0.84,  2.42,  0.13, -0.49, -0.44,  0.46, -0.69, -1.45,  0.57, -1.02, -0.02, -0.94,  1.10, -0.48, -0.71, -0.50, -1.63, -1.17, -2.18, -1.34, -0.29, -0.47)
  B = tensor_spline(x,xi_1,xi_2)
  return(20*B%*%cbind(beta))
}

f4 = function(x) {
  xi_1 = c(0.2,0.2,0.2,0.2,0.6)
  xi_2 = c(0.5,0.5,0.5,0.5,0.7)
  beta = c(0.83, -0.28, -0.36,  0.09,  2.25,  0.83,  1.31,  2.50,  1.17, -0.43, -1.00, -1.11, -0.06,  1.17,  1.05,  0.06, -0.74,  0.93,  1.67,  0.56, -0.75,  1.26, 0.04,  0.19,  0.46, -0.43,  0.02,  0.70,  0.97, -0.62, -0.86,  0.07, -1.05, -2.75, -1.13, -0.86,  1.56,  1.02,  1.04, -1.12, -1.07,  0.97,  0.17, -0.90,  0.16, -0.50, -0.97, -0.11, 1.09, -1.21, -1.77, -0.49,  0.32,  1.46,  1.54, -0.34, -1.08, -1.49, -0.25, -0.12, -0.65,  0.31,  0.12, -0.84)
  B = tensor_spline(x,xi_1,xi_2)
  return(20*B%*%cbind(beta))
}
```

```{r}
p = 0.025 # censored threshold
n_exp = 20 # experiment number
mse_array = array(dim=c(4,5,n_exp))
dim_names = list(c("Case 1","Case 2","Case 3","Case 4"),c("EBARS 1","EBARS 2","EBARS 3","TPS", "TEP"))
dimnames(mse_array) = dim_names
fs = list(f1,f2,f3,f4)
noises = c(1,1.5,2,2)
```

```{r}
set.seed(1234)
```

+ Run Simulation

```{r, include=FALSE}
time.start = Sys.time()
# m_train = 500; m_test = 200
m_train = 1000; m_test = 500

for(k in c(1:n_exp)) {
cat(paste0("The ",k,"-th experiment \n"))
for(i in c(1:4)) {
f = fs[[i]]; noise = noises[i]
# generate train data
x_train = cbind(c(0,runif(m_train-2,0,1),1),c(0,runif(m_train-2,0,1),1))
y_train = f(x_train)
y_obs = y_train + rnorm(m_train,0,noise)
x_new = cbind(runif(m_test,0,1),runif(m_test,0,1))
y_new = f(x_new)

if(FALSE) {
# EBARS with gamma = 1
binebars_1 = binebars(x_train, y_obs,gamma=1,times_1=3,times_2=3,intercept_1=T,intercept_2=T)
binebars_1$mcmc(burns=500,steps=500)
y_ebars_1 = binebars_1$predict(x_new)
mse_array[i,1,k] = mean(sort((y_new-y_ebars_1)^2)[round(p*m_test):round((1-p)*m_test)])

# EBARS with gamma = 0.5
binebars_2 = binebars(x_train, y_obs,gamma=0.5,times_1=1,times_2=1,intercept_1=T,intercept_2=T)
binebars_2$mcmc(burns=500,steps=500)
y_ebars_2 = binebars_2$predict(x_new)
mse_array[i,2,k] = mean(sort((y_new-y_ebars_2)^2)[round(p*m_test):round((1-p)*m_test)])

# EBARS with gamma = 0
binebars_3 = binebars(x_train, y_obs,gamma=0,times_1=0.5,times_2=0.5,intercept_1=T,intercept_2=T)
binebars_3$mcmc(burns=500,steps=500)
y_ebars_3 = binebars_3$predict(x_new)
mse_array[i,3,k] = mean(sort((y_new-y_ebars_3)^2)[round(p*m_test):round((1-p)*m_test)])
}

# Thin Plate Spline
x_train_df = data.frame(x1 = x_train[,1], x2 = x_train[,2])
x_new_df = data.frame(x1 = x_new[,1], x2 = x_new[,2])
model_tps = gam(y_obs~s(x1, x2, k = 200), data = x_train_df)
y_tps = predict(model_tps,x_new_df)
mse_array[i,4,k] = mean(sort((c(y_new)-y_tps)^2)[round(p*m_test):round((1-p)*m_test)])

# Tensor Product Spline
model_tep = gam(y_obs~te(x1, x2, k = 15), data = x_train_df)
y_tep = predict(model_tep, x_new_df)
mse_array[i,5,k] = mean(sort((c(y_new)-y_tep)^2)[round(p*m_test):round((1-p)*m_test)])
}
}
time.end = Sys.time()
print(time.end-time.start)
# Time difference of 1.616453 hours
# Time difference of 3.32217 hours
```

```{r}
mse_mean = array(dim=c(4,5),dimnames = dim_names) # mean of mse
mse_sd = array(dim=c(4,5),dimnames = dim_names) # sd of mse
mse = data.frame(array(dim=c(4,5),dimnames = dim_names))

for(i in 1:4) {
  for(j in 1:5) {
    mse_mean[i,j] = mean(mse_array[i,j,])
    mse_sd[i,j] = sd(mse_array[i,j,])
    mse[i,j] = paste0(round(mse_mean[i,j],digits=3),"(",round(mse_sd[i,j],digits=3),")")
  }
}

print(mse)
```

+ Write tables
```{r}
write.csv(mse,file=file.path("tables","surface_mse-1000.csv"))
```
